BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    BoxLayout:
        Button:
            text: 'Clear'
            on_press: app.handle_clear()
        TextInput:
            size_hint_x: 3
            id: input_name
            text: ''
    BoxLayout:
        Button:
            text: 'Greet'
            on_press: app.handle_greet()
        Label:
            size_hint_x: 3
            id: output_label
            text: 'Enter your name'
            color: (1, 1, 0, 1)